### ISSUE TITLE
Issue while running where in c2 server

### ISSUE THREAD

**Issue by raghavmishra** [mnemonic-no/SNIcat#3]
Hi Guys,
Can you please look into the below issue encountered while running 'where' command,

nicat-c2#where
(*) WAITING for yummy SNI form the agent - will timeout in 5 seconds
(*) - 226 bytes received in buffer
[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1123)
(*) - 226 bytes received in buffer
[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1123)
(*) - 226 bytes received in buffer
[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1123)
(*) - 229 bytes received in buffer
[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1123)
(*) - 228 bytes received in buffer
[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1123)
(*) - 228 bytes received in buffer
[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1123)
(*) - 226 bytes received in buffer
[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1123)
(*) - 229 bytes received in buffer
[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1123)
(*) - 226 bytes received in buffer
(*) RECEIVED: CD-DkY8WvGBuXZidfnB b32 PAYLOAD
(!)'Non-base32 digit found' exception while decoding SNI in 'parseSniPayload' - exiting thread
Traceback (most recent call last):
  File "/opt/SNIcat/snicat_c2.py", line 599, in <module>
    main()
  File "/opt/SNIcat/snicat_c2.py", line 596, in main
    socketLoop()
  File "/opt/SNIcat/snicat_c2.py", line 521, in socketLoop
    prompt = retrieveCmdWrapperAndSetPrompt(inputValue,0,0)
  File "/opt/SNIcat/snicat_c2.py", line 373, in retrieveCmdWrapperAndSetPrompt
    prompt_folder = (retrieveCmd(in_value.upper(),arg,arg2)).rstrip('\x00')
AttributeError: 'NoneType' object has no attribute 'rstrip'

I don't know why I am getting the exception. I have also tried to change the b32decode method as well. I had change to have casefold=True as the encoded value has lower case letters.

**Comment by THELEMITED** [comment]
There's a typo in the agent field it might be drawing the tables as a form instead of an encrypted statement bypassing the message system altogether and you get altruism codes though...

Clear(alt//pQ) !layer3.dns
